version: '3'

services:
  seating:
    build: .
    container_name: seating
    network_mode: host
    # volumes:
      # - hostPath:containerPath:ro
    ports:
      - '3000:3000'
#    depends_on:
#      - mongo
    # create .env file with the following env variables
    #  dbconn=mongodb://server_address:port
    env_file:
      - .env
    
#  mongo:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - '27017:27017'