package attendeeadapter

import "seating/internal/app/domain"

var demoAttendees []domain.Attendee = []domain.Attendee{
	{
		Name:        "Bob Davis",
		ID:          "1",
		Industry:    "Office Equipment & Copiers",
		CompanyName: "Cartridge World",
	},
	{
		Name:        "Elisa Zieg",
		ID:          "2",
		Industry:    "Non-Profit Organization",
		CompanyName: "The Sparrow's Nest Maternity Home",
	},
	{
		Name:        "Ben Motil",
		ID:          "3",
		Industry:    "Community",
		CompanyName: "City of O'Fallon",
	},
	{
		Name:        "Kris Kinsinger",
		ID:          "4",
		Industry:    "Window Treatments",
		CompanyName: "Two Blind Guys",
	},
	{
		Name:        "Anna Alt",
		ID:          "5",
		Industry:    "Home Improvement",
		CompanyName: "LSL Finishes",
	},
	{
		Name:        "Danielle Fristoe",
		ID:          "6",
		Industry:    "Health & Wellness",
		CompanyName: "Melaleuka Wellness Company",
	},
	{
		Name:        "Betty Bauer",
		ID:          "7",
		Industry:    "Insurance Services",
		CompanyName: "Compass Health Consultants - Healthcare Solutions Team",
	},
	{
		Name:        "Nicolas Ippolito",
		ID:          "8",
		Industry:    "Accountants & Tax Preparation",
		CompanyName: "Managerial Accounting Service",
	},
	{
		Name:        "Jim Mason",
		ID:          "9",
		Industry:    "Travel Services",
		CompanyName: "The Cruise & Travel Planner",
	},
	{
		Name:        "Kathy Fleming",
		ID:          "10",
		Industry:    "Human Resource Services",
		CompanyName: "People Solutions Center",
	},
	{
		Name:        "Jodie Uhlemeyer",
		ID:          "11",
		Industry:    "Pain Management",
		CompanyName: "Arch Advanced Pain Management - Find A Better You",
	},
	{
		Name:        "Brad Henningfeld",
		ID:          "12",
		Industry:    "Financial Services",
		CompanyName: "Principal Financial Group",
	},
	{
		Name:        "Matt Buetow",
		ID:          "13",
		Industry:    "Financial Services",
		CompanyName: "Principal Financial Group",
	},
	{
		Name:        "Ann Lubieswki",
		ID:          "14",
		Industry:    "Travel Services",
		CompanyName: "Travel by Ann",
	},
	{
		Name:        "Rodney Schrum",
		ID:          "15",
		Industry:    "Text Message Marketing",
		CompanyName: "Ameritext",
	},
	{
		Name:        "Angie Harness",
		ID:          "16",
		Industry:    "Real Estate: Residential",
		CompanyName: "Keller Williams - Angie Harness",
	},
	{
		Name:        "Heidi Martin",
		ID:          "17",
		Industry:    "Financial Services",
		CompanyName: "Principal Financial Group",
	},
	{
		Name:        "Linda Otto",
		ID:          "18",
		Industry:    "Retail Shopping",
		CompanyName: "Patty-Cakes of St. Louis",
	},
	{
		Name:        "Mary Agan",
		ID:          "19",
		Industry:    "Insurance Services",
		CompanyName: "Kathy Kilo Peterson State Farm",
	},
	{
		Name:        "Caitlyn Baratti",
		ID:          "20",
		Industry:    "Insurance Services",
		CompanyName: "Haight Insurance Agency, LLC",
	},
	{
		Name:        "Lindsey Helland",
		ID:          "21",
		Industry:    "Winery",
		CompanyName: "Cedar Lake Cellars",
	},
	{
		Name:        "Stephanie DiCiro",
		ID:          "22",
		Industry:    "Winery",
		CompanyName: "Cedar Lake Cellars",
	},
	{
		Name:        "Katie Worzel",
		ID:          "23",
		Industry:    "Health & Wellness",
		CompanyName: "Cornerstone Care",
	},
	{
		Name:        "Rick Nies",
		ID:          "24",
		Industry:    "Home Improvement",
		CompanyName: "MidWest SoftWash",
	},
	{
		Name:        "Skip Stephens",
		ID:          "25",
		Industry:    "Fire Protection",
		CompanyName: "Cottleville Fire Protection",
	},
	{
		Name:        "Wil Skaggs",
		ID:          "26",
		Industry:    "Fire Protection",
		CompanyName: "Cottleville Fire Protection",
	},
	{
		Name:        "Deanna Hoffman",
		ID:          "27",
		Industry:    "Retail Shopping",
		CompanyName: "Touchstone Crystal Jewelry by Swarovski",
	},
	{
		Name:        "Dan Tripp",
		ID:          "28",
		Industry:    "Coffee House",
		CompanyName: "Alpha & Omega Roasting Company",
	},
	{
		Name:        "Greg Kinder",
		ID:          "29",
		Industry:    "Civic Organizations",
		CompanyName: "O'Fallon Lions Club",
	},
	{
		Name:        "Kim Henson",
		ID:          "30",
		Industry:    "Marketing: Sales Promotions",
		CompanyName: "Circle of Marketing",
	},
	{
		Name:        "Brian Richardson",
		ID:          "31",
		Industry:    "Radio Station",
		CompanyName: "99.9 FM KFAV & 730 AM KWRE Kaspar Broadcasting",
	},
	{
		Name:        "Shelley Barr",
		ID:          "32",
		Industry:    "Radio Station",
		CompanyName: "104.5 FM KSLQ",
	},
	{
		Name:        "Rich Johns",
		ID:          "33",
		Industry:    "Restoration: Fire & Flood",
		CompanyName: "CATCO Catastrophe Cleaning & Restoration Company",
	},
	{
		Name:        "Jennifer Begley",
		ID:          "34",
		Industry:    "Banks",
		CompanyName: "Reliance Bank",
	},
	{
		Name:        "Katy Kruze",
		ID:          "35",
		Industry:    "Radio Station",
		CompanyName: "K-Wulf 101.7FM",
	},
}
